#!/bin/bash
action=$1
target=$2
args=$@

BASE_DIR=/opt
ORIGINAL_PORT=9999
ORIGINAL_VERSION=v1.0.0
ORIGINAL_ENTRANCE=entrance
ORIGINAL_USERNAME=username
ORIGINAL_PASSWORD=password

function usage() {
    echo "PanelX 控制脚本"
    echo
    echo "Usage: "
    echo "  ./pxctl [COMMAND] [ARGS...]"
    echo "  ./pxctl --help"
    echo
    echo "Commands: "
    echo "  status              查看 PanelX 服务运行状态"
    echo "  start               启动 PanelX 服务"
    echo "  stop                停止 PanelX 服务"
    echo "  restart             重启 PanelX 服务"
    echo "  uninstall           卸载 PanelX 服务"
    echo "  user-info           获取 PanelX 用户信息"
    echo "  listen-ip           切换 PanelX 监听 IP"
    echo "  version             查看 PanelX 版本信息"
    echo "  reset               重置 PanelX 系统信息"
    echo "  restore             恢复 PanelX 服务及数据"
}
function status() {
    systemctl status panelx.service
}
function start() {
    systemctl start panelx.service
    status
}
function stop() {
    systemctl stop panelx.service
    status
}
function restart() {
    systemctl restart panelx.service
    status
}
function uninstall() {
    read -p "卸载将会完全清除 PanelX 服务和数据目录，是否继续 [y/n] : " yn
    if [ "$yn" == "Y" ] || [ "$yn" == "y" ]; then
        echo -e "================== 开始卸载 PanelX Linux 服务器运维管理面板 =================="
        echo -e ""
        echo -e "1) 停止 PanelX 服务进程..."
        systemctl stop panelx.service
    else
        exit 0
    fi

    echo -e "2) 删除 PanelX 服务和数据目录..."
    rm -rf $BASE_DIR/panelx /usr/local/bin/{pxctl,panelx} /etc/systemd/system/panelx.service

    echo -e "3) 重新加载服务配置文件..."
    systemctl daemon-reload
    systemctl reset-failed

    echo -e ""
    echo -e "================================== 卸载完成 =================================="
}
function user-info() {
    panelx user-info
}
function listen-ip() {
    panelx listen-ip
}
function listen_ipv4() {
    panelx listen-ip ipv4
    restart
}
function listen_ipv6() {
    panelx listen-ip ipv6
    restart
}
function restore() {
    read -p "PanelX 将会恢复至上一个稳定版本，是否继续 [y/n] : " yn
    if [ "$yn" == "Y" ] || [ "$yn" == "y" ]; then
        echo -e ""
        panelx restore
        systemctl daemon-reload
        restart
        echo -e ""
        panelx version
    else
        exit 0
    fi
}
function version() {
    panelx version
}
function reset() {
    panelx reset
}
function reset_domain() {
    panelx reset domain
}
function reset_entrance() {
    panelx reset entrance
}
function reset_https() {
    panelx reset https
    restart
}
function reset_ips() {
    panelx reset ips
}
function reset_mfa() {
    panelx reset mfa
}

function main() {
    case "${action}" in
        status)
            status
            ;;
        start)
            start
            ;;
        stop)
            stop
            ;;
        restart)
            restart
            ;;
        restore)
            restore
            ;;
        uninstall)
            uninstall
            ;;
        user-info)
            user-info
            ;;
        listen-ip)
            case "${target}" in
                ipv4)
                    listen_ipv4
                    ;;
                ipv6)
                    listen_ipv6
                    ;;
                *)
                    listen-ip
                    ;;
            esac
            ;;
        version)
            version
            ;;
        reset)
            case "${target}" in
                domain)
                    reset_domain
                    ;;
                entrance)
                    reset_entrance
                    ;;
                https)
                    reset_https
                    ;;
                ips)
                    reset_ips
                    ;;
                mfa)
                    reset_mfa
                    ;;
                *)
                    reset
                    ;;
            esac
            ;;
        help)
            usage
            ;;
        --help)
            usage
            ;;
        *)
        echo "不支持的参数，请使用 help 或 --help 参数获取帮助"
    esac
}
main